### ISSUE TITLE
`from_str_radix` panicking with decimal

### ISSUE THREAD

**Issue by xphoniex** [kaidokert/fixed-bigint-rs#36]
```rust
let P = Bn::<u8, 64>::from_str_radix(
    "115792089237316195423570985008687907853269984665640564039457584007908834671663",
    10,
)
.unwrap();

// thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }'
```

hex, or base 16 works just fine though. I'm lookig at `fixeduint.rs` and in the examples radices of `{ 2, 8, 16 }` are being tested. Is `10` supported too, or is this a bug?

**Comment by kaidokert** [comment]
Uh, sorry for delayed response. No, base 10 or any other radix besides power of twos aren't implemented at all, i should have put a more explicit error in there. 

The TODO list mentions:
> Decimal string to/from conversion, currently only binary and hex strings are supported.

To be honest, i wrote this crate as a Rust learning exercise and trying to study how compact BigInt can be on Cortex-M0 and other low-end MCUs. I've since found that `crypto-bigint` pretty much does everything that this crate does, only better: https://github.com/kaidokert/fixed-bigint-rs/issues/26. It actually produces more compact code for RSA calcs and such.

**Comment by xphoniex** [comment]
Ah, I see.

Well, first thanks for this crate. Yours is one of the two options which compile for Arduino target (8-bit), `crypto-bigint` doesn't support that atm.

In my case, I'm implementing ecdsa and got a working solution using your code, and easy to read, however couldn't get memory usage down due to new allocation on every operation, so imagine you allocate another 64-byte number every time you do an addition, etc on Arduino Uno which has only 2048-byte ram.

Later I found [awint](https://github.com/AaronKutch/awint), which might also be interesting to you as well, however the code is now way more verbose, yet memory's much more controllable.

**Comment by kaidokert** [comment]
Thanks for the pointer to `awint`, hadn't come across it, i'll take a look at their implementation.

Strictly speaking this crate doesn't _allocate_, e.g. no heap, but it does probably trash a lot of stack yes. The ops that could trivially be done in-place ( e.g. [addition](https://github.com/kaidokert/fixed-bigint-rs/blob/main/src/fixeduint.rs#L182) ) are, but not everything is ( [shl](https://github.com/kaidokert/fixed-bigint-rs/blob/main/src/fixeduint.rs#L861) , [multiply]( https://github.com/kaidokert/fixed-bigint-rs/blob/main/src/fixeduint.rs#L235) , [div](https://github.com/kaidokert/fixed-bigint-rs/blob/main/src/fixeduint.rs#L235) ). With 2k RAM that runs out quick
